### PR TITLE
Adjust for overclock

### PR DESCRIPTION
**Pull request by Layer812**
It's not so critical, please merge it when you have time.

### CODE REVIEW

**Comment by fhoedemakers** [comment]
Will look into this tomorrow. Did you also noticed that the sound of the built-in game is not as good as other games when using the external speaker?

**Comment by Layer812** [comment]
OK, I got it. It's not good sound for built-in game. I'll find cause of this, and solve it :)
This weekend I'll go camping to mount side so, I'll try it on next week.

**Comment by fhoedemakers** [comment]
Hi, 
NewSchool pushed some sound updates over the weekend. The sound of the built-in game is much better now. You can check it in the newschool branch.
I also made some changes. Speaker selection and volume are saved to flash now, so it will be remembered the next time. For this to work, you need to reset to the menu. (Cannot flash immeadiately , because this often crashes the system)

Frank

**Comment by Layer812** [comment]
I also checked the newschool's branch.
It seems good, but it limits sound resolution (1280steps to 256steps).
The bug was overflow in calculate volume.

**Comment by Layer812** [comment]
I also found "click noise bug" in the code...I fixed it.

**Pull request merged**
