### PR TITLE
Add speaker

### PR DESCRIPTION
**Pull request by Layer812**
I've add some code and procedure for Adding speaker.

### CODE REVIEW

**Comment by fhoedemakers** [comment]
Hi,
Thanks for the pull-request. 

There is another contributor who has done the exactly the same mod. I'll look into both and see what works best.

**Comment by fhoedemakers** [comment]
See [this branch](https://github.com/fhoedemakers/PicoSystem_InfoNes/tree/NewSchool) for more info

**Comment by Layer812** [comment]
Newschool's implement  supports volume control, so it's better than mine. 
We can change playback frequency on 8ohm speaker from 10Khz to 122Khz
 I'm writing it below.
hardware.hpp  :  PWM_RANGE_BITS (14)  >  PWM_RANGE_BITS (10) 
hardware.cpp :   PWM_RANGE_BITS (14)  >  PWM_RANGE_BITS (10) 
main.cpp:        
  final_wave[fw_wr][i] =((unsigned char)wave1[i] + (unsigned char)wave2[i] + (unsigned char)wave3[i] + (unsigned char)wave4[i] + (unsigned char)wave5[i]) / 5;
>
   final_wave[fw_wr][i] = ((unsigned char)wave1[i] + (unsigned char)wave2[i] + (unsigned char)wave3[i] + (unsigned char)wave4[i] + (unsigned char)wave5[i]) * 1024 / 1280;  // 10bit resolution

**Comment by fhoedemakers** [comment]
Hi,

Not sure how to change this.

I guess, in main.cpp,

final_wave[fw_wr][i] =((unsigned char)wave1[i] + (unsigned char)wave2[i] + (unsigned char)wave3[i] + (unsigned char)wave4[i] + (unsigned char)wave5[i]) / 5;

must be replaced by:

final_wave[fw_wr][i] = ((unsigned char)wave1[i] + (unsigned char)wave2[i] + (unsigned char)wave3[i] + (unsigned char)wave4[i] + (unsigned char)wave5[i]) * 1024 / 1280; // 10bit resolution


But i'm not sure with hardware.hpp and hardware.cpp.

**Comment by fhoedemakers** [comment]
Or is it ok that I merge the newschool branch to main? You can then add your changes, and create a new pull request.
It must work however with both the built-in as the added speaker. Speakers can be selected with Y + Down.

Let me know.

Thanks!

Frank

**Comment by fhoedemakers** [comment]
Done! By the way, I guess you are living in Japan. Is it well past midnight now there... 😉

**Comment by fhoedemakers** [comment]
Closed pull request.

**Comment by Layer812** [comment]
Yes, I'm living in Japan also in "IT time zone" :)

**Pull request closed without merging**
